redis-ha:
  enabled: false

server:
  replicas: 1
  httproute:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: shared-public-nlb
        namespace: istio-system
        sectionName: https
    hostnames:
      - "argocd.demosfelipetrindade.lat"

repoServer:
  replicas: 1

applicationSet:
  replicas: 1
