global:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Equal
      value: "true"
      effect: NoSchedule

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  extraArgs:
    - --insecure
