redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  extraArgs:
    - --insecure
  httproute:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: shared-public-alb
        namespace: infra
        sectionName: https
    hostnames:
      - "argocd.demosfelipetrindade.lat"
