apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-stores
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys: [name]
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: Exists
          - clusters:
              selector:
                matchLabels:
                  environment: dev
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}-external-secrets-stores"
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      source:
        repoURL: '{{ metadata.annotations.gitops_repo_url }}'
        targetRevision: "{{ metadata.annotations.gitops_repo_revision }}"
        path: k8s/environments/{{ metadata.annotations.environment }}/addons/external-secrets-stores
        kustomize:
          patches:
            - target:
                kind: ClusterSecretStore
                name: aws-secretsmanager
              patch: |
                - op: replace
                  path: /spec/provider/aws/region
                  value: "{{ metadata.annotations.aws_region }}"
      destination:
        name: "{{ name }}"
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
