apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-api-crds
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys: [name]
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: Exists
              values:
                targetRevision: v1.5.1
          - clusters:
              selector:
                matchLabels:
                  environment: dev
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}-gateway-api-crds"
    spec:
      project: default
      source:
        repoURL: https://github.com/kubernetes-sigs/gateway-api
        path: config/crd/standard
        targetRevision: "{{ values.targetRevision }}"
      destination:
        name: "{{ name }}"
        namespace: gateway-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
