apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-api
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys: [name]
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: Exists
          - clusters:
              selector:
                matchLabels:
                  environment: dev
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}-gateway-api"
    spec:
      project: default
      source:
        repoURL: '{{ metadata.annotations.gitops_repo_url }}'
        targetRevision: "{{ metadata.annotations.gitops_repo_revision }}"
        path: k8s/environments/{{ metadata.annotations.environment }}/addons/gateway-api
        kustomize:
          patches:
            - target:
                kind: Gateway
                name: shared-public-nlb
              patch: |
                - op: replace
                  path: /spec/infrastructure/annotations/service.beta.kubernetes.io~1aws-load-balancer-ssl-cert
                  value: "{{ metadata.annotations.acm_certificate_arn }}"
      destination:
        name: "{{ name }}"
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
