apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys: [name]
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: Exists
              values:
                chart: base
                chartVersion: 1.29.2
          - clusters:
              selector:
                matchLabels:
                  environment: dev
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}-istio-base"
    spec:
      project: default
      sources:
        - repoURL: https://istio-release.storage.googleapis.com/charts
          chart: '{{ values.chart }}'
          targetRevision: '{{ values.chartVersion }}'
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/k8s/environments/default/addons/istio-base/values.yaml
              - $values/k8s/environments/{{ metadata.annotations.environment }}/addons/istio-base/values.yaml
        - repoURL: '{{ metadata.annotations.gitops_repo_url }}'
          targetRevision: "{{ metadata.annotations.gitops_repo_revision }}"
          ref: values
      destination:
        name: "{{ name }}"
        namespace: istio-system
      # istiod mutates failurePolicy from Ignore to Fail at runtime when ready
      # https://github.com/istio/istio/issues/52785
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istiod-default-validator
          jsonPointers:
            - /webhooks/0/failurePolicy
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
