apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: karpenter-resources
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys: [name]
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: Exists
          - clusters:
              selector:
                matchLabels:
                  environment: dev
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}-karpenter-resources"
    spec:
      project: default
      source:
        repoURL: '{{ metadata.annotations.gitops_repo_url }}'
        targetRevision: "{{ metadata.annotations.gitops_repo_revision }}"
        path: k8s/environments/{{ metadata.annotations.environment }}/addons/karpenter-resources
        kustomize:
          patches:
            - target:
                kind: EC2NodeClass
                name: default
              patch: |
                - op: replace
                  path: /spec/role
                  value: "{{ metadata.annotations.karpenter_node_role_name }}"
            - target:
                kind: EC2NodeClass
                name: default
              patch: |
                - op: replace
                  path: /spec/subnetSelectorTerms/0/tags/karpenter.sh~1discovery
                  value: "{{ metadata.annotations.cluster_name }}"
            - target:
                kind: EC2NodeClass
                name: default
              patch: |
                - op: replace
                  path: /spec/securityGroupSelectorTerms/0/tags/karpenter.sh~1discovery
                  value: "{{ metadata.annotations.cluster_name }}"
            - target:
                kind: EC2NodeClass
                name: default
              patch: |
                - op: replace
                  path: /spec/tags/Name
                  value: "karpenter-{{ metadata.annotations.cluster_name }}"
      destination:
        name: "{{ name }}"
        namespace: karpenter
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 30
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
