apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys: [name]
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: Exists
              values:
                chart: metrics-server
                chartVersion: 3.13.0
          - clusters:
              selector:
                matchLabels:
                  environment: dev
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}-{{ values.chart }}"
    spec:
      project: default
      sources:
        - repoURL: https://kubernetes-sigs.github.io/metrics-server/
          chart: '{{ values.chart }}'
          targetRevision: '{{ values.chartVersion }}'
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/k8s/environments/default/addons/{{ values.chart }}/values.yaml
              - $values/k8s/environments/{{ metadata.annotations.environment }}/addons/{{ values.chart }}/values.yaml
        - repoURL: '{{ metadata.annotations.gitops_repo_url }}'
          targetRevision: "{{ metadata.annotations.gitops_repo_revision }}"
          ref: values
      destination:
        name: "{{ name }}"
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
